### ISSUE TITLE
add a generic passthrough mechanism

### ISSUE THREAD

**Issue by rjbs** [rjbs/Dist-Zilla-PluginBundle-RJBS#5]
for example, in:

```
[@RJBS]
MakeMaker.bananas = 12
```

recognize that "bananas = 12" is to be passed to to the plugin named MakeMaker; prefix accounting matters

this can go in something like Easy, if it works

**Comment by karenetheridge** [comment]
This can be done with Dist::Zilla::Role::PluginBundle::Config::Slicer. (See my bundle, where I also have a bit of code to reach into the payload to munge around the slice params in a few cases, e.g. to add on to existing lists rather than overwrite them.)

I actually came to this issue queue to file a ticket requesting that you add Config::Slicer and Dist::Zilla::Role::PluginBundle::PluginRemover, so as to enable adding this option to Dist-Zilla's dist.ini:

```
Test::ReportPrereqs.include = JSON::PP
```

...in order to try to get to the bottom of the mysterious JSON::PP-related travis failures, e.g. at https://s3.amazonaws.com/archive.travis-ci.org/jobs/78275410/log.txt
